--liquibase formatted sql

--changeset mk:001-init dbms:postgresql

CREATE TABLE app_user (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(200) NOT NULL,
    login    VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    CONSTRAINT uq_app_user_login UNIQUE (login)
);

CREATE TABLE partner (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(200) NOT NULL,
    zip     VARCHAR(20) NOT NULL,
    city    VARCHAR(100) NOT NULL,
    address VARCHAR(300) NOT NULL,
    phone   VARCHAR(50)
);

CREATE TABLE category (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_category_id BIGINT,
    name               VARCHAR(100) NOT NULL,
    CONSTRAINT fk_category_parent
        FOREIGN KEY (parent_category_id) REFERENCES category (id),
    CONSTRAINT ck_category_not_own_parent
        CHECK (parent_category_id <> id)
);

CREATE TABLE product (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200) NOT NULL,
    category_id BIGINT,
    description TEXT,
    price       NUMERIC(19, 2) NOT NULL,
    CONSTRAINT fk_parent_category
        FOREIGN KEY (category_id) REFERENCES category (id),
    CONSTRAINT ck_product_price CHECK (price >= 0)
);


CREATE TABLE invoice (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number VARCHAR(100) NOT NULL,
    partner_id     BIGINT NOT NULL,
    date           DATE NOT NULL,
    price          NUMERIC(19, 2) NOT NULL,
    CONSTRAINT uq_invoice_number UNIQUE (invoice_number),
    CONSTRAINT fk_invoice_partner
        FOREIGN KEY (partner_id) REFERENCES partner (id),
    CONSTRAINT ck_invoice_price CHECK (price >= 0)
);

CREATE TABLE invoice_item (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    amount     NUMERIC(12, 3) NOT NULL,
    tax        NUMERIC(5, 2) NOT NULL,
    price      NUMERIC(19, 2) NOT NULL,
    CONSTRAINT fk_invoice_item_invoice
        FOREIGN KEY (invoice_id) REFERENCES invoice (id),
    CONSTRAINT fk_invoice_item_product
        FOREIGN KEY (product_id) REFERENCES product (id),
    CONSTRAINT ck_invoice_item_amount CHECK (amount > 0),
    CONSTRAINT ck_invoice_item_tax CHECK (tax BETWEEN 0 AND 100),
    CONSTRAINT ck_invoice_item_price CHECK (price >= 0)
);

CREATE INDEX idx_invoice_partner_id
    ON invoice (partner_id);

CREATE INDEX idx_invoice_item_invoice_id
    ON invoice_item (invoice_id);

CREATE INDEX idx_invoice_item_product_id
    ON invoice_item (product_id);

CREATE INDEX idx_category_parent_id
    ON category (parent_category_id);